# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pre_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='explanation',
        ),
        migrations.AlterField(
            model_name='answer',
            name='textAnswer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='expectedTextAnswer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
